name: Docker Image CI For GHCR
on:
  push
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        run: |
          docker login --username virayuth4 --password ${{secrets.GH_PAT_SERVER}} ghcr.io
          docker build . --tag ghcr.io/virayuth4/zingowebservernode3:latest
          docker push ghcr.io/virayuth4/zingowebservernode3:latest